# specify language
language:
  - python
# specify python version(s)
python:
  - "3.8.3"
# install dependencies
install:
  - pip install -r requirements.txt

env:
  - APP_SETTINGS="config.DevelopmentConfig"
# run tests
script:
  - nosetests

